concurrency:
  cancel-in-progress: true
  group: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    ) && format('ci-buildcache-{0}', github.sha) || format('ci-buildcache-{0}', github.ref)
    }}
jobs:
  seed-build-cache:
    name: ${{ matrix.os }}, ${{ matrix.jdk }} seed build cache
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 50
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
        S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
        S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
      name: Build Calcite
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --scan --no-parallel --no-daemon build -x test
        job-id: jdk${{ matrix.jdk }}
        remote-build-cache-proxy-enabled: false
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 8
        - 11
        - 17
        os:
        - ubuntu
        - macos
        - windows
      max-parallel: 3
name: Seed build cache
on:
  repository_dispatch:
    types: trigger-ga___buildcache.yml
