jobs:
  publish-website:
    needs: sync-main-site
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: site
    - continue-on-error: true
      name: Build site
      run: 'docker compose run -e JEKYLL_UID=$(id -u) -e JEKYLL_GID=$(id -g) build-site

        '
      working-directory: site
    - continue-on-error: true
      name: Build javadoc
      run: 'docker compose run generate-javadoc

        '
      working-directory: site
    - continue-on-error: true
      env:
        CALCITE_WEBSITE_BUILD: ${{ secrets.CALCITE_WEBSITE_BUILD }}
      name: Push site
      run: "git config --global init.defaultBranch main\ngit init                \
        \           # Turn the folder into a git repo\ngit config url.\"https://asf-ci-deploy:$CALCITE_WEBSITE_BUILD@github.com/\"\
        .insteadOf \"https://github.com/\"\ngit config user.email ${{ github.actor\
        \ }}@users.noreply.github.com\ngit config user.name ${{ github.actor }}\n\
        git remote add origin https://github.com/apache/calcite-site\ngit fetch  \
        \                        # Pull from the calcite-site repo\ngit reset origin/main\
        \ --soft     # Bring in changes from the calcite-site repo, but keep our local\
        \ changes\ngit reset -- avatica/              # Restore the avatica site\n\
        git checkout -- avatica/\ngit add .\nif ! git diff-index --quiet HEAD; then\n\
        \  git commit -m \"Website deployed from calcite@$GITHUB_SHA\"\n  git push\
        \ origin main\nfi\n"
      working-directory: site/target
  sync-main-site:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: site
    - continue-on-error: true
      name: Sync main and site branches
      run: 'git reset --hard origin/main

        git push --force origin site

        '
name: Publish website on release
on:
  repository_dispatch:
    types: trigger-ga___publish-website-on-release.yml
